### ISSUE TITLE
output images from two-tail test of one-way t-tests (matlab_TFCE) 

### ISSUE THREAD

**Issue by gargiris** [markallenthornton/MatlabTFCE#7]
Hello,

I have a question regarding the image output when using the function "matlab_TFCE" with analysis "oneway". As I understand from the documentation, there should be two images as output (one for the negative tail and one for the positive tail):
% If tails == 2, two such output images will be returned, one for the
% 'positive' tail and one for the 'negative' tail of the test,
% respectively.
However, when I run the function, only one output image is produced. Can you help me with this? Thank you very much.

Georgette

**Comment by markallenthornton** [comment]
Hi Georgette,

For the 'onesample' analysis option, you should indeed get two output images, as the documentation describes.  Are you using the following syntax?

[pcorr_pos,pcorr_neg] = matlab_tfce(analysis,2,imgs,imgs2,covariate,nperm,H,E,C,dh,parworkers,nuisance)

It's important to "catch" both outputs with the "[pcorr_pos,pcorr_neg] =" bit of the code. The output to a single variable seems like the likely reason you might be experiencing this issue.

Best,
Mark
